apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: helm-watcher-role
  namespace: wego-system
rules:
  - apiGroups:
      - helm.watcher
    resources:
      - helmrepositories
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - helm.watcher
    resources:
      - helmrepositories/finalizers
    verbs:
      - create
      - delete
      - get
      - patch
      - update
  - apiGroups:
      - helm.watcher
    resources:
      - helmrepositories/status
    verbs:
      - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: helm-watcher-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: helm-watcher-role
subjects:
  - kind: ServiceAccount
    name: helm-watcher
    namespace: wego-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: helm-watcher
  namespace: wego-system
